# Generated by Django 4.2.6 on 2023-10-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='core.menumodel', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterUniqueTogether(
            name='menumodel',
            unique_together={('name', 'parent')},
        ),
    ]
